Add ability to display time more readable
custom-components/sensor.yandex_maps pull request #14
Opened 2020-12-03 19:28 UTC by h4

New attribute `friendly_time` added. It allows to display time more readable, without additional templates.

Also added option to configure sensor with common lat_lng coordinates, instead of lng_lat requested by yandex.

2020-12-19 08:23 UTC, h4 commented
Hi @ludeeus! Could you look at this PR please?

2021-01-13 13:43 UTC, ludeeus requested changes

2021-01-13 13:43 UTC, ludeeus commented on README.md
> +[![custom_updater][customupdaterbedge]][customupdater]
```suggestion
```

2021-01-13 13:43 UTC, ludeeus commented on README.md
> +[customupdaterbedge]: https://img.shields.io/badge/custom__updater-true-success.svg
```suggestion
```

2021-01-13 13:43 UTC, ludeeus commented on custom_components/yandex_maps/sensor.py
> +                    self._state = int(info.get('direct', {}).get('time'))
```suggestion
                    self._state = info.get('direct', {}).get('time')
```
States are always strings

2021-01-13 13:43 UTC, ludeeus commented on custom_components/yandex_maps/sensor.py
> +        _LOGGER.debug('Passed time: %s', minutes)
```suggestion
    def humanize(cls, minutes):
        minutes = int(minutes)
        _LOGGER.debug('Passed time: %s', minutes)
```

2021-06-18 23:56 UTC, closed without merging